// filepath: ios/HABITRY/Podfile
platform :ios, '12.0'
use_frameworks!
inherit_deep_link_settings

target 'HABITRY' do
  pod 'Capacitor', '~> 8.3'
  pod 'CapacitorStatusBar', '~> 8.3'
  pod 'CapacitorSplashScreen', '~> 8.3'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end